### ISSUE TITLE
[P2] Key Conflict with InventoryInteraction and Carry Script

### ISSUE THREAD

**Issue by Charlieranderson** [adanter/Prairie#11]
Currently there is a conflict if scripts from both inventory systems are attached to the same object.

**Comment by yinghj** [comment]
Current status: 
If both are attached to one object, on left click, the object will go to inventory first.
Then once dropped out of inventory, it will be carried on cursor.

**Comment by yinghj** [comment]
Idea 1:
- Similar to annotation prompt, directions hover over the object 
- Need to solve orders and conflicts when multiple prompts appear

**Comment by yinghj** [comment]
1/9 Discussion:
Similar to how annotation is handled
In FirstPersonInteractor.cs, 
```
if (i is Annotation)
{
    // special cases, handled by `AttemptReadAnnotation`
    continue;
}
```
We can also add `if (i is InventoryInteraction || Carry)  continue;`

then in `void Update ()` have a 
```
if (Input.GetKeyDown (KeyCode.A)) {
    this.AttemptAddToInventory (); 
}
if (Input.GetKeyDown (KeyCode.C)) {
    this.AttemptCarry (); 
}
```

**Comment by yinghj** [comment]
Attempt 1 to resolve the bug:
https://github.com/adanter/Prairie/commit/41d6c37c51f61a6fc5ceea15f00857b6bc197835
