### ISSUE TITLE
[P2] Key conflict Inventory vs Pause Menu

### ISSUE THREAD

**Issue by yinghj** [adanter/Prairie#12]
After entering the Inventory UI interaction state, key esc should be exiting the cursor freeze and inventory interaction state, but it also brings up the pause menu. Resume has to be clicked to go back to the game.

**Comment by Charlieranderson** [comment]
We should have a separate keybind for freeing the cursor to interact with the inventory. That will also have to freeze the player.

**Comment by yinghj** [comment]
We already have that. It's key 'I' for interacting with UI and 'Q' for returning to game state. 
Details see doc: https://docs.google.com/document/d/1koPAH5PzNfJWK09M0Mq55nD_XrdP4072wBiA8GVJ7n4/edit#heading=h.uac8uvuoxfvh

**Comment by yinghj** [comment]
Removing 'ESC' as an option for returning to game state from inventory UI fixes this issue: https://github.com/adanter/Prairie/pull/14/commits/37f96f3cfe70495d0426379c0460051600e15de8

**Comment by yinghj** [comment]
Closed by pull request #14
