### ISSUE TITLE
[P1] Objects are still allowed to be 'added' to inventory if inventory is full. 

### ISSUE THREAD

**Issue by yinghj** [adanter/Prairie#13]
Objects will disappear after inventory interaction is triggered when inventory is full.
They are not stored in the array, and setActive to false.

**Comment by yinghj** [comment]
Fix: https://github.com/adanter/Prairie/commit/e5b4913c9085fc9fd719fbec992b2486d4d2162b

**Comment by Charlieranderson** [comment]
if we have a fix for it, should we close the issue?

**Comment by yinghj** [comment]
We will close this once the fix is actually pulled to master.

**Comment by yinghj** [comment]
Closed by pull request #14
