### ISSUE TITLE
[P0] Journal Script not attached correctly on Prairie Player Prefab

### ISSUE THREAD

**Issue by yinghj** [adanter/Prairie#20]
We need to save and push a new Prairie Player Prefab with Journal Script correctly attached. 

Should be done by whoever is actively working on that prefab now to prevent conflicts.

**Comment by Charlieranderson** [comment]
Re-adding the prefab with it attached correctly does not work, and the error message given is hard to reproduce and sporadic.

**Comment by yinghj** [comment]
closed by commit 6067405de1c593976cb43c49451bf21c82e3dd08
